@host = http://
@dominio = localhost
@port = :3500
@endpoint = /auth
@apiurl = {{host}}{{dominio}}{{port}}{{endpoint}}
@ContentType = application/json; charset=UTF-8

GET {{apiurl}}

###

GET {{apiurl}}/2

###

POST {{apiurl}}/register
Content-Type: {{ContentType}}
 
{
  "name": "prova 020",
  "password": "020",
  "email" : "provara020@fatec.com"
}

###

POST {{apiurl}}/Login
Content-Type: {{ContentType}}
 
{
  "name": "prova 020",
  "password": "020",
  "email" : "provara020@fatec.com"
}

###
DELETE {{apiurl}}/4